[package]
name = "advent2020-rust"
version = "0.1.0"
authors = ["Lang Martin <lang.martin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
substring = "1.4.0"
lazy_static = "1.4.0"